### ISSUE TITLE
Issue loading spec dependencies

### ISSUE THREAD

**Issue by mandrews** [cantino/huginn_agent#13]
I've recently started development on a Huginn Agent gem - things are going pretty smoothly, and I can load the agent via `ADDITIONAL_GEMS` in the `.env`. However, I ran into a bit of a snag- I'm having trouble loading a `spec.add_development_dependency` via the `gemspec` for use in a spec file.  When I move the dependency over to a `spec.add_runtime_dependency` all is well 😄 

Modification to scaffolding:
```diff
--- a/my_agents.gemspec
+++ b/my_agents.gemspec
@@ -20,6 +20,7 @@ Gem::Specification.new do |spec|

   spec.add_development_dependency 'bundler', '~> 1.7'
   spec.add_development_dependency 'rake', '~> 10.0'
+  spec.add_development_dependency 'faker'

   spec.add_runtime_dependency 'huginn_agent'
 end

--- a/spec/my_agent_spec.rb
+++ b/spec/my_agent_spec.rb
@@ -1,9 +1,10 @@
 require 'rails_helper'
 require 'huginn_agent/spec_helper'
+require 'faker' 

 describe Agents::MyAgent do
+  let(:base_url) { Faker::Internet.url }
```

Stacktrace:
```
$ rake spec
Running specs ...
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's 'rails' settings.
[Coveralls] Outside the CI environment, not sending data.
$HOME/.rvm/gems/ruby-2.2.4@my_agents/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- faker (LoadError)

rake aborted!

$HOME/.rvm/gems/ruby-2.2.4@my_agents/gems/huginn_agent-0.5.0/lib/huginn_agent/spec_runner.rb:61:in `shell_out'
$HOME/.rvm/gems/ruby-2.2.4@my_agents/gems/huginn_agent-0.5.0/lib/huginn_agent/spec_runner.rb:42:in `block in spec'
$HOME/.rvm/gems/ruby-2.2.4@my_agents/gems/huginn_agent-0.5.0/lib/huginn_agent/spec_runner.rb:41:in `chdir'
$HOME/.rvm/gems/ruby-2.2.4@my_agents/gems/huginn_agent-0.5.0/lib/huginn_agent/spec_runner.rb:41:in `spec'
$HOME/.rvm/gems/ruby-2.2.4@my_agents/gems/huginn_agent-0.5.0/lib/tasks/spec.rake:19:in `block in <top (required)>'
$HOME/.rvm/gems/ruby-2.2.4@my_agents/bin/ruby_executable_hooks:15:in `eval'
$HOME/.rvm/gems/ruby-2.2.4@my_agents/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => spec
(See full trace by running task with --trace)
```

I've also tried adding this to the Gemfile and using Bundler to load
```diff
diff --git a/Gemfile b/Gemfile
index ae5f7bd..5622574 100644
--- a/Gemfile
+++ b/Gemfile
@@ -6,3 +6,7 @@ gem 'huginn_agent', '~> 0.5.0'

+group :test do
+  gem 'faker'
+end

--- a/spec/my_agent_spec.rb
+++ b/spec/my_agent_spec.rb
@@ -1,9 +1,11 @@
 require 'rails_helper'
 require 'huginn_agent/spec_helper'
+require 'bundler/setup'
+Bundler.require(:default, :test)
```

**Comment by dsander** [comment]
Hi @mandrews,

that is an interesting problem, I did not think about development dependencies until now :)

Does it work if you put the gem into the `Gemfile` without using a group?

**Comment by dsander** [comment]
That did not work :)

Like you mentioned it works to add the required gem to the runtime_dependencies. That is the case because when running the specs the Agent gem will be loaded by Huginn the same way it is done when actually using the gem (in which case the development dependencies are really not needed).

I am not sure if there is a way to include a gems development dependencies when loading it in the Gemfile.

What does work is adding the faker gem to the `runtime_dependencies` only when running the specs:
```ruby
  if ENV['RAILS_ENV'] == 'test'
    spec.add_runtime_dependency "faker"
  end
```

If we need to go that route `huginn_agent` would set a special environment variable like `HUGINN_AGENT_SPEC_RUNNER`. This avoids requiring the gem when running Huginn's specs with the Agent gem included in `ADDITIONAL_GEMS`.

**Comment by mandrews** [comment]
@dsander - that works! I could see the `HUGINN_AGENT_SPEC_RUNNER` approach working.  Out of curiosity, I did a bit of hacking around I got the development gems to load via `ADDITONAL_GEMS` in the `spec_runner.rb`:

```
diff --git a/lib/huginn_agent/spec_runner.rb b/lib/huginn_agent/spec_runner.rb
index 1994185..be9d370 100644
--- a/lib/huginn_agent/spec_runner.rb
+++ b/lib/huginn_agent/spec_runner.rb
@@ -47,7 +47,11 @@ class HuginnAgent
       print message if message

       (status, output) = Bundler.with_clean_env do
-        ENV['ADDITIONAL_GEMS'] = "#{gem_name}(path: ../../)"
+        gem_file = File.expand_path(Dir['../../*.gemspec'].first)
+        # TODO: seems like this should be handled at ADDITONAL_GEMS eval time
+        loaded_gems = ['bundler', 'rake', 'huginn_agent']
+        development_gems = Gem::Specification.load(gem_file).development_dependencies.map(&:name).reject { |x| loaded_gems.include?(x) }
+        ENV['ADDITIONAL_GEMS'] = ["#{gem_name}(path: ../../)", development_gems].join(',')
```

One issue with this approach is that duplicate gems need to be stripped from `ADDITONAL_GEMS`, otherwise the gem load will fail within the cloned version of Huginn's `Gemfile`:
```
Tried executing 'bundle exec rspec -r $HOME/Development/huginn_agent/lib/huginn_agent/patches/coverage.rb --pattern ../*_spec.rb,../{[!huginn/]}**/*_spec.rb'
$HOME/.rvm/gems/ruby-2.2.4@my_agents/gems/bundler-1.14.6/lib/bundler/dsl.rb:103:in `gem':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: bundler (>= 1.5.0) and bundler (>= 0). Bundler cannot continue.

 #  from $HOME/Development/dpa/my_agents/spec/huginn/Gemfile:204
 #  -------------------------------------------
 #  GemfileHelper.parse_each_agent_gem(ENV['ADDITIONAL_GEMS']) do |args|
 >    gem *args
 #  end
 #  -------------------------------------------
```
I could see also patching Huginn to make the Gemfile more robust against duplicate/conflicting `ADDITONAL_GEMS`

**Comment by mandrews** [comment]
@dsander I found another possible solution. It's nice b/c you can add gems to the gemspec as usual , only issue is that it requires patching the `huginn/Gemfile`:

```ruby
# my_huginn_agent/my_huginn_agent.gemspec
Gem::Specification.new do |spec|
  ...
  spec.add_development_dependency 'bundler', '~> 1.7'
  spec.add_development_dependency 'rake', '~> 12.0'
  spec.add_development_dependency 'byebug'
  spec.add_development_dependency 'faker'
  spec.add_development_dependency 'factory_girl'

  spec.add_runtime_dependency 'huginn_agent'
end

# my_huginn_agent/spec/spec_helper.rb
base_path = File.expand_path('../../', __FILE__)
$LOAD_PATH.unshift "#{base_path}/lib"

require_relative 'huginn/spec/rails_helper'

require 'my_huginn_agent' # AKA lib/my_huginn_agent.rb
HuginnAgent.require! # Force HuginnAgent.require! 

Dir["#{base_path}/spec/support/**/*.rb"].each { |f| require f }

# my_huginn_agent/spec/huginn/Gemfile
...

# Should probably be encapsulated in ENV
base_path = File.expand_path('../../../', __FILE__)
gemspec = Dir["#{base_path}/*.gemspec"].first
previous_gems = dependencies.map(&:name)
development_gems = Gem::Specification.load(gemspec).development_dependencies.each do |args|
  # Might be able to detect and warn of conflicts here
  next if previous_gems.include?(args.name)
  gem args.name, *args.requirements_list 
end
```

The documented `rake spec` works with this construction, but also a manual invocation works as well:
```bash
(cd spec/huginn; bundle exec rspec --require ../spec_helper.rb ../*_spec.rb)
```

This allows you to set a breakpoint with `byebug`, whereas the `popen3`/[`shell_out`](https://github.com/cantino/huginn_agent/blob/f4edd3f001ab85d6519ba7800bd66f3d878b5698/lib/huginn_agent/spec_runner.rb#L46) caused some STDIN inference

**Comment by dsander** [comment]
Thanks again, `0.6.0` fixes the issue.
